plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
    id 'com.google.dagger.hilt.android'
}

android {
    namespace 'com.bencobble.inventorytracker'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "com.bencobble.inventorytracker"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'androidx.cardview:cardview:1.0.0'

    // Hilt
    implementation 'com.google.dagger:hilt-android:2.59.2'
    annotationProcessor 'com.google.dagger:hilt-compiler:2.59.2'

    // Firebase
    implementation platform('com.google.firebase:firebase-bom:34.13.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'

    // Navigation Component
    implementation 'androidx.navigation:navigation-fragment:2.9.0'
    implementation 'androidx.navigation:navigation-ui:2.9.0'

    // MPAndroidChart
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

    // Testing
    testImplementation libs.junit
    testImplementation 'org.mockito:mockito-core:5.14.0'
    testImplementation 'androidx.arch.core:core-testing:2.2.0'
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
